### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by JaredCubilla** [antris/sneakpeek#1]
Hi, project looks awesome. Could you add a `bower.json` so that people could access and download it through Bower?

**Comment by antris** [comment]
Hey Jared and thanks for the feedback! I added a `bower.json` and registered the package. I hope I did it correctly, never used Bower myself. :)

Do you want to check that I did everything correctly?

**Comment by antris** [comment]
I managed to install it through `bower install` so I'm closing this.

**Comment by JaredCubilla** [comment]
Yay! Thanks.
